sara_arm_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

sara_arm_controller:
  type: "velocity_controllers/JointTrajectoryController"
  publish_rate: 50               # default: 50
  joints:
    - sara_arm_joint_1
    - sara_arm_joint_2
    - sara_arm_joint_3
    - sara_arm_joint_4
    - sara_arm_joint_5


  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 0.5
